# update the submodules on a weekly interval
version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: "weekly"
  # update actions used in zizmor-scan.yaml on a weekly interval
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "*"
        patterns:
          - ".github/workflows/zizmor-scan.yaml"
